### ISSUE TITLE
English command not working on macOS

### ISSUE THREAD

**Issue by liyishuai** [nondanee/vsc-netease-music#21] opened 2019-03-16 23:51 UTC
Pressed "command + shift + P" and entered "netease" in the command palette, but no command had shown. Chinese commands worked.

**Comment by nondanee** [comment] 2019-03-17 00:46
See last line in [Known issue](https://github.com/nondanee/vsc-netease-music/blob/master/README.md#known-issue),  duplicate of #17

**Closed** 2019-03-17 01:32 UTC
